# Site settings
title: Yang Lab
email: yangjl0930@gmail.com
description: > # this means to ignore newlines until "baseurl:" It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  Jinliang Yang's lab at UNL for plant quantitative genetics and
  statistical genomics research.
baseurl: "/labwebsite" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: JinliangYang
github_username:  jyanglab
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
