---
layout: page
title: Publications
permalink: /pub/
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results="asis"}
library(methods)
library(scholar)
myid <- "2CiKnzkAAAAJ"
bob <- get_profile(myid)
cat(paste0("__[H-Index](https://scholar.google.com/citations?hl=en&user=2CiKnzkAAAAJ)__ [ __", bob$h_index, "__ ] (", bob$total_cites, " citations as of ", date(), ")  "))

bob <- get_publications("2CiKnzkAAAAJ")
file <- "data/gs_cites.txt"
if(file.exists(file)){
  oldf <- read.delim(file)
  newf <- merge()
}

### Cite IEEE style
#write.table(bob, "data/gs_cites.txt", sep="\t", row.names=FALSE, quote=FALSE)
```

-----------------------------------

## preprint


-----------------------------------

## 2015


```{r, echo=FALSE, results="asis"}
pid <- bob[bob$pubid=="u-x6o8ySG0sC",]
cat(paste0(
"__J. Yang__, H. Jiang, C. T. Yeh, J. Yu, J. A. Jeddeloh, D. Nettleton, and P. S. Schnable, __Extreme-phenotype genome-wide association study (XP-GWAS): A method for identifying trait-associated variants by sequencing pools of individuals selected from a diversity panel__ *Plant J., vol. 84, no. 3, pp. 587–596, 2015.*  \n",
"> [Abstract](http://doi.wiley.com/10.1111/tpj.13029) ",
"| [PDF](http://onlinelibrary.wiley.com/doi/10.1111/tpj.13029/epdf) ",
"| 10.1111/tpj.13029 ",
"| [cited ", pid$cites, "](", "https://scholar.google.com/scholar?oi=bibs&hl=en&cites=", pid$cid, "&as_sdt=5)"))
```

```{r, echo=FALSE, results="asis"}
pid <- bob[bob$pubid=="UeHWp8X0CEIC",]
cat(paste0(
"D. Sosso, D. Luo, Q. Li, J. Sasse, __J. Yang__, G. Gendrot, M. Suzuki, K. E. Koch, D. R. McCarty, P. S. Chourey, P. M. Rogowsky, J. Ross-Ibarra, B. Yang, and W. B. Frommer, __Seed filling in domesticated maize and rice depends on SWEET-mediated hexose transport__,* Nat. Genet., vol. 47, no. 12, pp. 1489–1493, 2015.*  \n",

"> [Abstract](http://www.nature.com/ng/journal/v47/n12/full/ng.3422.html) ",
"| [PDF](http://www.nature.com/ng/journal/v47/n12/pdf/ng.3422.pdf) ",
"| 10.1038/ng.3422 ",
"| [cited ", pid$cites, "](", "https://scholar.google.com/scholar?oi=bibs&hl=en&cites=", pid$cid, "&as_sdt=5)"))
```

```{r, echo=FALSE, results="asis"}
pid <- bob[bob$pubid=="IjCSPb-OGe4C",]
cat(paste0(
"S. Leiboff, X. Li, H.-C. Hu, N. Todt, __J. Yang__, X. Li, X. Yu, G. J. Muehlbauer, M. C. P. Timmermans, J. Yu, P. S. Schnable, and M. J. Scanlon, __Genetic control of morphometric diversity in the maize shoot apical meristem__, *Nat. Commun., vol. 6, p. 8974, 2015.*  \n",

"> [Abstract](http://www.nature.com/ncomms/2015/151120/ncomms9974/full/ncomms9974.html) ",
"| [PDF](http://www.nature.com/ncomms/2015/151120/ncomms9974/pdf/ncomms9974.pdf) ",
"| 10.1038/ncomms9974 ",
"| [cited ", pid$cites, "](", "https://scholar.google.com/scholar?oi=bibs&hl=en&cites=", pid$cid, "&as_sdt=5)"))
```

------------------------------

## 2014 and Before 

```{r, echo=FALSE, results="asis"}
pid <- bob[bob$pubid=="2osOgNQ5qMEC",]
cat(paste0(
  "S. Liu, K. Ying, C.-T. Yeh, __J. Yang__, R. Swanson-Wagner, W. Wu, T. Richmond, D. J. Gerhardt, J. Lai, N. Springer, D. Nettleton, J. A. Jeddeloh, and P. S. Schnable, __Changes in genome content generated via segregation of non-allelic homolog__, *Plant J., vol. 72, no. 3, pp. 390–9, Nov. 2012.*  \n",

"> [Abstract](http://onlinelibrary.wiley.com/doi/10.1111/j.1365-313X.2012.05087.x/abstract) ",
"| [PDF](http://onlinelibrary.wiley.com/doi/10.1111/j.1365-313X.2012.05087.x/epdf) ",
"| 10.1111/j.1365-313X.2012.05087.x ",
"| [cited ", pid$cites, "](", "https://scholar.google.com/scholar?oi=bibs&hl=en&cites=", pid$cid, "&as_sdt=5)"))
```


```{r, echo=FALSE, results="asis"}
pid <- bob[bob$pubid=="9yKSN-GCB0IC",]
cat(paste0(
  "L. Koesterke, D. Stanzione, M. Vaughn, S. M. Welch, W. Kusnierczyk, __J. Yang__, C.-T. Yeh, D. Nettleton, and P. S. Schnable, __An Efficient and Scalable Implementation of SNP-Pair Interaction Testing for Genetic Association Studies__, *2011 IEEE Int. Symp. Parallel Distrib. Process. Work. Phd Forum, pp. 523–530, May 2011.*  \n",

"> [Abstract](http://ieeexplore.ieee.org/document/6008872/?arnumber=6008872) ",
"| [PDF](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6008872) ",
"| 10.1111/j.1365-313X.2012.05087.x ",
"| [cited ", pid$cites, "](", "https://scholar.google.com/scholar?oi=bibs&hl=en&cites=", pid$cid, "&as_sdt=5)"))
```

--------------------------

## Patent Applications

P. S. Schnable, A. OTT, __J. Yang J__, __Intercrossed ex-PVP lines__.  *2014. PENDING.*

P. S. Schnable, __J. Yang__, __Identification of QTLs and trait-associated SNPs controlling six yield component traits in maize__. *2013. PENDING.*

P. S. Schnable, __J. Yang__, R. A. Swanson-Wagner, D. Nettleton, __QTL regulating ear productivity traits in maize__. *U.S. Patent No. 8779233. Filed July 12, 2011.*


-----------------------

```{r, eval=FALSE, echo=FALSE}
source("data/googleCite.r")
out = googleCite("https://scholar.google.com/citations?hl=en&user=2CiKnzkAAAAJ",pdfname="figure/wordcloud.pdf")
```




